evklidHTMLCSS
Mysterio0535/Evklid pull request #1
Opened 2023-04-22 09:37 UTC by Mysterio0535

2023-04-22 10:14 UTC, BroadenYourMind commented
<img width="1571" alt="Screenshot 2023-04-22 at 12 13 30" src="https://user-images.githubusercontent.com/102143527/233777885-76896eb7-bb91-47bf-b327-27e56122fea2.png">

Так не должно быть. Пользователь, не должен иметь возможность выйти за контейнер, а быть только в поле контента

2023-04-22 10:19 UTC, BroadenYourMind commented
<img width="777" alt="Screenshot 2023-04-22 at 12 18 01" src="https://user-images.githubusercontent.com/102143527/233778079-63ed619d-9ec7-4f75-a778-d52799190313.png">

Когда навожу на эту кнопку мышкой, смешается блок, такого быть не должно

2023-04-22 10:20 UTC, BroadenYourMind commented
<img width="276" alt="Screenshot 2023-04-22 at 12 19 37" src="https://user-images.githubusercontent.com/102143527/233778110-46bf2e93-f615-4567-935a-9e3ffb09416d.png">

По-моему, это должно быть ссылкой. Сейчас просто картинка

2023-04-22 10:21 UTC, BroadenYourMind commented
<img width="275" alt="Screenshot 2023-04-22 at 12 20 55" src="https://user-images.githubusercontent.com/102143527/233778166-faddac43-1f3d-4939-a8c0-024a9888aebf.png">

Я бы подсвечивал эти ссылки при наведении, так было бы понятней, что они активны

2023-04-22 11:24 UTC, BroadenYourMind requested changes

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                </li>
Поиск должен быть отдельно от навигации. А сам ul  обернут в тег nav (так поисковые роботы будут понимать, что тут находятся навигация сайта)

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                    <a href="" class="header__nav-link nav-link">
Зачем тут отдельно nav-link?

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <div class="section-hero__container-description">
section-hero__content

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                    <h1 class="section-hero__heading">Проектные решения любой сложности</h1>
section-hero__header

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <div class="section-hero__container-description">
А вообще лучше убрать этот  div и прописать все стили в блоке выше, чтоб не плодить лишние вложености

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +            <div class="container about-us__content">
Если начал блок с контейнером называть  {section-name}__conteiner, то всюду называй так же. Сложно потом будет ориентироваться, если в одной секции у тебя {section-name}__conteiner, в другой {section-name}__content, в тертией ещё чего, а логика всюду одна и так же.

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                        <div class="aboust-us__container-image-description">
лишняя вложеность

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <h2 class="container-header about-us__header">О нас</h2>
 Модификаторы прописывай через нижний дэфис "_"
container_header 

А то не понятно, где у тебя модификатор, а где просто класс с "-".

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                            </ul>
Это не список. Это просто текст и кнопка. Достаточно двух тегов

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                </nav>
Это не выглядит, как навигация, это просто список, с переключателями.

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                        </ul>
Это просто две кнопки, не список

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                        <img src="static/image/Rectangle 18.jpg" alt="">
Всегда прописывай  alt

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <div class="question__content question__content-one">
 модификатор через "_"

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                    <div class="question__content-btn-more">
Это не кнопка. Лишний блок.  Можешь этот класс прописать ниже

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <div class="footer__content">
Это не контент, это  nav

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                    <ul class="footer__social-icon-list">
Я бы просто 3 сслыки сделал тут, список лишний, как по мне

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <div class="footer__social-icon">
footer__social-icons*

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +                <ul class="footer__survey-list">
Это не список) Просто ипуты, что-то ты очень любишь списки)

2023-04-22 11:24 UTC, BroadenYourMind commented on index.html
> +            </form>
Форму нужно переделать. Сделай просто 2 инпута, текстарию, и внизу див с кнопкой (Именно кнопка должна быть) и чекбоксом.

2023-04-22 11:45 UTC, Mysterio0535 commented on index.html
> +                    <a href="" class="header__nav-link nav-link">
это общий клас , ниже есть тоже сылки с такими же параметрами

2023-04-22 11:50 UTC, Mysterio0535 commented on index.html
> +                <div class="section-hero__container-description">
это два разных контейнера : 1 контейнер это background-image (у него ширина и высота отличается от второго) , 2 контейнер с текстом

2023-04-22 16:44 UTC, BroadenYourMind commented on index.html
> +                    <a href="" class="header__nav-link nav-link">
Оки

2023-04-22 16:52 UTC, BroadenYourMind commented on index.html
> +                <div class="section-hero__container-description">
не вижу тут необходимости делать два контейнера, всё можно прописать в одном классе. Отступы до контента укажи через падинги, вот и всё

2023-04-22 16:57 UTC, Mysterio0535 commented on index.html
> +                        <div class="aboust-us__container-image-description">
у меня тогда ломается блок. Первый див это раскид дивов (image i content ) , а image-descritpion это текст на фото и + нижний фон к фото

2023-04-22 19:35 UTC, BroadenYourMind commented
<img width="320" alt="Screenshot 2023-04-22 at 21 35 00" src="https://user-images.githubusercontent.com/102143527/233803219-4f667e37-b37a-420b-a9ed-20391f156649.png">

На чекбок установи hover: pointer , это нужно делать для всех активных элементов

2023-04-22 19:36 UTC, BroadenYourMind commented
<img width="714" alt="Screenshot 2023-04-22 at 21 35 58" src="https://user-images.githubusercontent.com/102143527/233803265-e4640a10-c9cd-4366-8f4d-63025e242d1f.png">

Убери возможность растягивать  textaria

2023-04-22 19:41 UTC, BroadenYourMind commented on index.html
> +                        <div class="aboust-us__container-image-description">
Понял, тогда хорошо

2023-04-22 19:46 UTC, BroadenYourMind commented on index.html
> +                <div class="section-hero__container-description">
Тут так и не поправил.  Вот так должно быть. Только отступы правильные установи, а то я просто более-менее подходящие сделал

<img width="1571" alt="Screenshot 2023-04-22 at 21 46 21" src="https://user-images.githubusercontent.com/102143527/233803628-b615ad12-5ef2-4813-bbed-d4aad15ff7d6.png">

2023-04-22 19:53 UTC, BroadenYourMind commented
<img width="1228" alt="Screenshot 2023-04-22 at 21 52 11" src="https://user-images.githubusercontent.com/102143527/233803828-35758808-8137-4f9c-83e1-e1e4696ac0f4.png">
 
Отступы сделай через свойство  gap, а не через :not(:last-child) у дочерних элементов (это устаревший метод)

2023-04-22 20:03 UTC, BroadenYourMind commented
<img width="1535" alt="Screenshot 2023-04-22 at 21 58 54" src="https://user-images.githubusercontent.com/102143527/233804074-bb3d4b1f-e24d-450b-8ff8-59b2a2d6ca24.png">

1. Позиционируй блоки с absolute не через мажин, через свойства top, bottom, left, rigth. 
2. С помощь padding установи отступы для дочерних элементов.
3. Убери в дочерних элементов margin

2023-04-22 20:07 UTC, BroadenYourMind commented
<img width="396" alt="Screenshot 2023-04-22 at 22 05 29" src="https://user-images.githubusercontent.com/102143527/233804217-861b3f5e-2ad7-4ba3-890c-fdf4b759cb7b.png">


Всегда добавляй margin от левого элемента к правому, а не наоборот

2023-04-22 20:16 UTC, BroadenYourMind commented
<img width="1408" alt="Screenshot 2023-04-22 at 22 15 54" src="https://user-images.githubusercontent.com/102143527/233804585-b226c323-d28b-46c2-84b0-73b7c485e70e.png">

Отступы делай в самом контейнере, а не от дочернего элемента

2023-04-22 20:20 UTC, BroadenYourMind commented
<img width="994" alt="Screenshot 2023-04-22 at 22 19 07" src="https://user-images.githubusercontent.com/102143527/233804955-9ea58fa6-aedd-477b-a364-fe6ff09833c5.png">

Вместо того, чтоб указывать margin для среднего блока, укажи для каждого блока свойство flex: 0 0 {ширина в %}

2023-04-25 07:57 UTC, BroadenYourMind commented
<img width="1088" alt="Screenshot 2023-04-25 at 09 57 15" src="https://user-images.githubusercontent.com/102143527/234212050-78863943-60bb-46c5-9e7a-f6a01ef4d62f.png">

Так впритык контейнера и должно быть?

2023-04-25 08:01 UTC, BroadenYourMind commented
<img width="1563" alt="Screenshot 2023-04-25 at 09 58 12" src="https://user-images.githubusercontent.com/102143527/234212733-ce85de05-11e0-4512-a563-4cb301b7e430.png">

ширину картинкам, которые растягиваются на весь блок указывай не в точных (1920px), а в условных (100%) единицах, тогда не будет проблем, с тем, что блок будет улетать в неизвестность. И падинги подправить для всех расширений

2023-04-25 08:42 UTC, BroadenYourMind requested changes

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                            <a class="about-us__item-btn" href="">Подробней</a>
Эта кнопка не должна быть в position: absolute. Нужно переделать, а то при изменении экрана она вылетает за блок, так быть не должно. И название класса сделай по блоку уже about-us__container-image-description-btn

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                    <div class="about-work__content">
У этого блока убери max-heigth, при сужении экрана кнопки пропадают.

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                <div class="question__content question__content-one">
Эти блокам установи gap, чтоб при ссужении расширения экрана текст не был впритык с кнопкой.

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +        <div class="container footer__container">
Установи gap, чтоб при ссужении блоки не слипались

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                    <textarea name="textarea" cols="74" rows="10" placeholder="Сообщение"
инпутом и текстариа установи ширину 100%, а не фиксированную 570px, чтоб они были гибкими

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                    <br>
Зачем тут это br?

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                    </a>
Это должна быть именно кнопка, тег <button>, так как это форма

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +                    </label>
Закинь эту кнопку и чекбокс в div, и при сужении экрана сделай так, чтоб чекбокс смещался вверх.

2023-04-25 08:42 UTC, BroadenYourMind commented on index.html
> +            <div class="footer__left">
Убери с этого блока все отспупы. Указывай их в самом контейнере

2023-04-29 13:40 UTC, merged